# remote_theme: pages-themes/architect  # didn't work
theme: jekyll-theme-architect

collections:
    authors:
      output: true
  
defaults:
    - scope:
        path: ""
        type: "authors"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

baseurl: "/jekylltest"

# Andy added
assets: "/assets/css/styles.css"